#! /bin/bash

APIS="Common FullNode StorageMiner Gateway Wallet Worker"
__dirname="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $__dirname

output_dir="${__dirname}/../src/gen"
mkdir -p "$output_dir"

echo "Working ..."

# Generate common types first
./generate-common-types.sh

# Generate mod.rs to export all API modules
mod_file="${output_dir}/mod.rs"
echo "// Code generated by github.com/tangle-network/lotus-client-schema-rs/rust-schemagen. DO NOT EDIT." > ${mod_file}
echo "#![allow(unused, clippy::too_many_arguments)]" >> ${mod_file}
echo "pub mod types;" >> ${mod_file}

for api in $APIS; do
    api_lower=$(echo "$api" | tr '[:upper:]' '[:lower:]')
    output_file="${output_dir}/${api_lower}.rs"
    echo "// Code generated by github.com/tangle-network/lotus-client-schema-rs/rust-schemagen. DO NOT EDIT." > ${output_file}
    echo "" >> ${output_file}
    
    go run . $api >> ${output_file}
    echo " ... ${api}"
    
    # Add module declaration to mod.rs
    echo "pub mod ${api_lower};" >> ${mod_file}
done

echo "Wrote generated API to ${output_dir}"